/* 
 * Werewolf Engine
 *
 * This is a werewolf game engine for REST access. It is primarily developed for CPE200 class at Computer Engineering, Chiang Mai University.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: pruetboonma@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using WerewolfAPI.Client;
using WerewolfAPI.Api;
using WerewolfAPI.Model;

namespace WerewolfAPI.Test
{
    /// <summary>
    ///  Class for testing ChatApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ChatApiTests
    {
        private ChatApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ChatApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChatApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ChatApi
            //Assert.IsInstanceOfType(typeof(ChatApi), instance, "instance is a ChatApi");
        }

        
        /// <summary>
        /// Test ChatGameIDSessionIDChatIDGet
        /// </summary>
        [Test]
        public void ChatGameIDSessionIDChatIDGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? gameID = null;
            //string sessionID = null;
            //int? chatID = null;
            //var response = instance.ChatGameIDSessionIDChatIDGet(gameID, sessionID, chatID);
            //Assert.IsInstanceOf<List<ChatMessage>> (response, "response is List<ChatMessage>");
        }
        
        /// <summary>
        /// Test ChatGameIDSessionIDPost
        /// </summary>
        [Test]
        public void ChatGameIDSessionIDPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? gameID = null;
            //string sessionID = null;
            //ChatMessage body = null;
            //instance.ChatGameIDSessionIDPost(gameID, sessionID, body);
            
        }
        
    }

}
