/* 
 * Werewolf Engine
 *
 * This is a werewolf game engine for REST access. It is primarily developed for CPE200 class at Computer Engineering, Chiang Mai University.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: pruetboonma@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using WerewolfAPI.Client;
using WerewolfAPI.Api;
using WerewolfAPI.Model;

namespace WerewolfAPI.Test
{
    /// <summary>
    ///  Class for testing RoleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RoleApiTests
    {
        private RoleApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RoleApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RoleApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RoleApi
            //Assert.IsInstanceOfType(typeof(RoleApi), instance, "instance is a RoleApi");
        }

        
        /// <summary>
        /// Test GetRoleById
        /// </summary>
        [Test]
        public void GetRoleByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? roleId = null;
            //var response = instance.GetRoleById(roleId);
            //Assert.IsInstanceOf<Role> (response, "response is Role");
        }
        
        /// <summary>
        /// Test RoleGet
        /// </summary>
        [Test]
        public void RoleGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.RoleGet();
            //Assert.IsInstanceOf<List<Role>> (response, "response is List<Role>");
        }
        
    }

}
